version: '3.9'

services:
  app:
    container_name: ${PROJECT_TITLE}_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.deploy
    ports:
      - ${FAST_API_PORT}:8000
    volumes:
      - ../messanger_api/photos:/app/src/photos
    
    depends_on:
      - postgres
      - redis


  postgres:
    image: postgres:13.8-bullseye
    container_name: ${PROJECT_TITLE}_db
    restart: always
    env_file:
      - .env.deploy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - messanger:/var/lib/postgresql/data
    ports:
      - "5687:5432"

  redis:
    image: redis:6.2.7
    hostname: "${PROJECT_TITLE}-redis"
    restart: always
    container_name: ${PROJECT_TITLE}_redis
    user: ${REDIS_USER}

    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      # test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - "6357:6379"
    env_file:
      - .env.deploy

volumes:
  messanger:
    name: postgres

  redis_data:
    name: redis
  