version: '3.9'

services:
  app:
    container_name: ${PROJECT_TITLE}_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.deploy
    ports:
      - ${FAST_API_PORT}:8000


  postgres:
    image: postgres:13.8-bullseye
    container_name: ${PROJECT_TITLE}_db
    restart: always
    env_file:
      - .env.deploy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - messanger:/var/lib/postgresql/data
    ports:
      - "5687:5432"

volumes:
  messanger:
    name: postgres
