version: '3.9'

services:
  app:
    container_name: ${FAST_API_TITLE}_API
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - ${FAST_API_PORT}:8000


  db:
    image: postgres:13.8-bullseye
    container_name: ${FAST_API_TITLE}_DB
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  db:
    name: db
