version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    env_file:
      - .env
    ports:
      - ${FAST_API_PORT}:8000


  db:
    image: postgres:13.8-bullseye
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 2s
      timeout: 3s
      retries: 40

volumes:
  db:
    name: db
