version: '3.9'

services:
  app:
    container_name: ${PROJECT_TITLE}_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.deploy
    ports:
      - ${FAST_API_PORT}:8000
    volumes:
      - ../messanger_api/photos:/app/src/photos
    
    depends_on:
      - postgres


  postgres:
    image: postgres:13.8-bullseye
    container_name: ${PROJECT_TITLE}_db
    restart: always
    env_file:
      - .env.deploy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - messanger:/var/lib/postgresql/data
    ports:
      - "5687:5432"

  minio:
    image: minio/minio
    container_name: ${PROJECT_TITLE}-minio
    ports:
      - 8900:9000
      - 8901:9001
    volumes:
      - minio_storage:/data/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address "0.0.0.0:9001" /data/minio


volumes:
  messanger:
    name: postgres

  minio_storage: 
    name: minio